version: 0.2

phases:
  install:
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      
      # - echo "Installing Terraform version $TF_VERSION"
      # - wget -q https://releases.hashicorp.com/terraform/$${TF_VERSION}/terraform_$${TF_VERSION}_linux_amd64.zip
      # - unzip -q terraform_$${TF_VERSION}_linux_amd64.zip
      # - mv terraform /usr/local/bin/
      # - terraform --version
  
  pre_build:
    commands:
      - echo "=== TEST BUILD ==="
      - pwd
      - ls -l
      # - echo "=== AWS Identity Information ==="
      # - aws sts get-caller-identity
      # - echo "=== IAM Role Details ==="
      # - ROLE_NAME=$(aws sts get-caller-identity --query Arn --output text | cut -d'/' -f2)
      # - echo "Role Name: $ROLE_NAME"
      # - echo "=== Attached Policies ==="
      # - aws iam list-attached-role-policies --role-name $ROLE_NAME || true
      # - echo "=== Inline Policies ==="
      # - aws iam list-role-policies --role-name $ROLE_NAME || true
      # - echo "================================"
      # - echo "Initializing Terraform"
      # - cd $CODEBUILD_SRC_DIR
      # - terraform init
      # - terraform validate
  
  build:
    commands:
      - echo "Build Phase"
      # - echo "Planning Terraform changes"
      # - terraform plan -out=tfplan
      # - echo "Applying Terraform changes"
      # - terraform apply -auto-approve tfplan
  
  post_build:
    commands:
      - echo "POST-Build Phase"
      # - echo "Terraform apply completed on $(date)"
      # - terraform output -json > outputs.json

cache:
  paths:
    - '.terraform/**/*'
    - '.terraform.lock.hcl'
